project:
  type: website
  output-dir: docs


website:
  title: "Data_viz_guidelines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - brand_guide.qmd
      - graphics-guide.qmd

format:
  html:
    css: styles.css
    toc: true
    
